plugins {
    id 'fabric-loom' version '1.11.8'
}

version = "1.0.0"
group = "com.mustafa.optibest"

repositories {
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:1.21.8"
    mappings "net.fabricmc:yarn:1.21.8+build.1:v2"
    modImplementation "net.fabricmc:fabric-loader:0.16.0"

    // İşte sihirli satır:
    // Bu satır, libs klasöründeki her şeyi otomatik olarak projeye ekler.
    modImplementation fileTree(dir: 'libs', include: ['*.jar'])
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}
