name: Build Mod
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # gradlew dosyasını bulmaya çalış, yoksa hata verme devam et
      - name: Build with Gradle
        run: |
          if [ -f "./gradlew" ]; then
            chmod +x ./gradlew
            ./gradlew clean build
          else
            echo "gradlew bulunamadı, sistem gradle kullanılıyor..."
            gradle clean build
          fi

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OptiBest-Mod
          path: build/libs/
          
