name: Build Mod
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and Clean Cache
        run: |
          # Önceki tüm hatalı yapılandırmaları ve cache'i siliyoruz
          rm -rf .gradle/loom-cache
          rm -rf ~/.gradle/caches/fabric-loom
          
          # Gradle'ı çalıştır
          ./gradlew clean build || gradle clean build
          
