name: Build Mod
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Clean and Build
        run: |
          # 1. Her şeyi sil
          rm -rf .gradle
          rm -rf build
          # 2. Fabric Loom ayarlarını temizle
          rm -rf ~/.gradle/caches/fabric-loom
          # 3. Sıfırdan kur
          gradle clean build --no-daemon --refresh-dependencies

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: OptiBest-Build
          path: build/libs/
          
